### ISSUE TITLE
GPLv3+ or GPLv2+ for kbdd.

### ISSUE THREAD

**Issue by Vascom** [qnikst/kbdd#48]
All (almost) source code files have headers for GPLv2+, but COPYING file says GPLv3+. Please clarify it.

**Comment by Vascom** [comment]
GPL (v2 or later)
-----------------
kbdd-0.7.1/src/common-defs.h
kbdd-0.7.1/src/dbus/dbus-test.c
kbdd-0.7.1/src/dbus/m-kbdd-service.c
kbdd-0.7.1/src/dbus/m-kbdd-service.h
kbdd-0.7.1/src/kbdd.c
kbdd-0.7.1/src/libkbdd.c
kbdd-0.7.1/src/libkbdd.h
kbdd-0.7.1/src/perwindow.c
kbdd-0.7.1/src/perwindow.h

**Comment by qnikst** [comment]
Thanks. Fixed as in 0e1056f. Code was originally developed under GPL-2+.
